### ISSUE TITLE
FPGA: Failure on creating container if host OS does not have some python modules

### ISSUE THREAD

**Issue by kad** [intel/intel-device-plugins-for-kubernetes#191]
Failure on creating container if host OS does not have some python modules
9926ab6d6c925a68aabca7d84c545738/f7df405cbd7acf7222f144b0b93acd18: can't get bitstream info

```
/opt/intel/fpga-sw/opae/bin/packager 
jsonschema module has no validatiors() or exceptions()
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/intel/fpga-sw/opae/bin/packager/__main__.py", line 2, in <module>
  File "/opt/intel/fpga-sw/opae/bin/packager/packager.py", line 35, in <module>
  File "/opt/intel/fpga-sw/opae/bin/packager/afu.py", line 52, in <module>
ImportError: No module named jsonschema
```

**Comment by kad** [comment]
Resolved as part of PR #199. Python modules dependency dropped.
